version: "3.9"
services:
  sugc-backend:
    image: node:17.7.1
    command: "npm run dev"
    # build:
    #   context: ../../backend_saar
    #   dockerfile: Dockerfile
    container_name: sugc-backend
    user: "node"
    working_dir: /home/node/app
    volumes:
     - type: bind
       source: ../../backend
       target: /home/node/app 
     - type: bind
       source: ../../postman
       target: /home/node/postman 
    restart: unless-stopped
    hostname: node
    ports:
     - "4001:4001"
    environment:
      TZ: America/Guatemala
      ENV: DEV 
  # db:
  #   image: postgres:10.19
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   hostname: db.postgres-1
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data 
  #     - ./db:/docker-entrypoint-initdb.d
volumes:
  pgdata:

